name = "politicals-ws"
main = "src/index.js"
compatibility_date = "2024-12-24"

[durable_objects]
bindings = [
    { name = "GAME_ROOM", class_name = "GameRoom" }
]

[[migrations]]
tag = "v1"
new_classes = ["GameRoom"]

[observability.logs]
enabled = true
